/** The prompt-mode target library (images in client/public/targets, generated by a one-off content script). */
import type { Breakdown, Difficulty } from '../shared/types';
import { WORD_LIMITS } from '../shared/types';
import data from './targets.json';

export interface Target { id: string; theme: string; prompt: string; key: string; stealOptions: string[]; taboo: string[]; image: string; masked: string; maskFallback?: boolean }
export interface BotScore extends Breakdown { missed: string; tip: string }
export interface BotAttempt { name: string; draftPrompt: string; draftImage: string; draft: BotScore; finalPrompt: string; finalImage: string; final: BotScore }

const lib = data as unknown as { targets: Target[]; demo: Record<string, { artists: BotAttempt[]; imposter?: BotAttempt }> };
export const TARGETS: Target[] = lib.targets;
export const DEMO_BOTS = lib.demo;
/** The two solo-demo rounds: a bot is the imposter on the first, the human on the second. */
export const DEMO_TARGETS = ['frog-band', 'cat-dj'];
export const targetById = (id: string) => TARGETS.find((t) => t.id === id);

/** Match 0-100 from the five areas. The style modifier counts style and color double. */
export function matchOf(b: Breakdown, styleRound = false) {
  const w = styleRound ? { subject: 1, details: 1, style: 2, color: 2, composition: 1 } : { subject: 1, details: 1, style: 1, color: 1, composition: 1 };
  const total = (Object.keys(w) as (keyof Breakdown)[]).reduce((n, k) => n + Math.max(0, Math.min(20, b[k])) * w[k], 0);
  const max = (Object.values(w) as number[]).reduce((a, x) => a + x, 0) * 20;
  return Math.round((total / max) * 100);
}

/** Words that break this round's rule, or null. Limits depend on difficulty (normal: draft 8, final 30). Taboo bans the obvious words (and simple plurals). */
export function promptProblem(text: string, pass: 'draft' | 'final', taboo: string[] | null, difficulty: Difficulty = 'normal'): string | null {
  const t = text.trim();
  if (!t) return 'Write a prompt first.';
  if (t.length > 320) return 'Keep it under 320 characters.';
  const words = t.split(/\s+/).length;
  const max = WORD_LIMITS[difficulty][pass];
  if (words > max) return `Your ${pass} can be at most ${max} words (you have ${words}).`;
  for (const w of taboo || []) {
    if (new RegExp(`\\b${w.replace(/[^a-z0-9]/gi, '')}(s|es)?\\b`, 'i').test(t)) return `“${w}” is a taboo word this round. Describe it another way.`;
  }
  return null;
}

/** The daily target: one per UTC day, the same for everyone, stepping through the library so neighbours differ. */
export function dailyKey(now = Date.now()) { return new Date(now).toISOString().slice(0, 10); }
export function dailyTarget(key = dailyKey()): Target {
  const days = Math.floor(Date.UTC(+key.slice(0, 4), +key.slice(5, 7) - 1, +key.slice(8, 10)) / 86_400_000);
  return TARGETS[(days * 7) % TARGETS.length];
}

/**
 * Placeholder bots for any target without recorded content, so the solo game can use the whole library.
 * Artists "produce" the target itself (a strong match); the imposter produces the masked version, which is
 * exactly what someone who couldn't see the hidden detail would make. Clearly labelled as practice bots in the UI.
 */
export function placeholderBots(t: Target): { artists: BotAttempt[]; imposter: BotAttempt } {
  const words = t.prompt.split(/\s+/);
  const short = words.slice(0, 7).join(' ');
  const noKey = t.prompt.replace(new RegExp(t.key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i'), 'something').replace(/\s+/g, ' ');
  const score = (subject: number, details: number, style: number, color: number, composition: number, missed: string, tip: string): BotScore => ({ subject, details, style, color, composition, missed, tip });
  const artist = (i: number): BotAttempt => ({
    name: `bot${i}`, draftPrompt: short, draftImage: t.masked, draft: score(13, 9, 11, 12, 12, 'the details are rough', 'Name the setting and the lighting.'),
    finalPrompt: words.slice(0, Math.max(10, words.length - i * 2)).join(' '), finalImage: t.image, final: score(17 - i, 15 - i, 16, 16 - i, 15, 'a few small props', 'Mention the art style by name.'),
  });
  return {
    artists: [artist(0), artist(1), artist(2)],
    imposter: { name: 'imp', draftPrompt: short.replace(/\b(a|an|the)\b\s+\S+$/i, 'something'), draftImage: t.masked, draft: score(10, 6, 10, 11, 10, 'the main object is missing', 'Look closer at the drafts.'),
      finalPrompt: noKey, finalImage: t.masked, final: score(12, 5, 14, 14, 12, `${t.key} is missing`, 'The hidden detail was the point.') },
  };
}
