/** The prompt-mode target library (images in client/public/targets, generated by a one-off content script). */
import type { Breakdown } from '../shared/types';
import data from './targets.json';

export interface Target { id: string; theme: string; prompt: string; key: string; stealOptions: string[]; taboo: string[]; image: string; masked: string; maskFallback?: boolean }
export interface BotScore extends Breakdown { missed: string; tip: string }
export interface BotAttempt { name: string; draftPrompt: string; draftImage: string; draft: BotScore; finalPrompt: string; finalImage: string; final: BotScore }

const lib = data as unknown as { targets: Target[]; demo: Record<string, { artists: BotAttempt[]; imposter?: BotAttempt }> };
export const TARGETS: Target[] = lib.targets;
export const DEMO_BOTS = lib.demo;
/** The two solo-demo rounds: a bot is the imposter on the first, the human on the second. */
export const DEMO_TARGETS = ['frog-band', 'cat-dj'];
export const targetById = (id: string) => TARGETS.find((t) => t.id === id);

/** Match 0-100 from the five areas. The style modifier counts style and color double. */
export function matchOf(b: Breakdown, styleRound = false) {
  const w = styleRound ? { subject: 1, details: 1, style: 2, color: 2, composition: 1 } : { subject: 1, details: 1, style: 1, color: 1, composition: 1 };
  const total = (Object.keys(w) as (keyof Breakdown)[]).reduce((n, k) => n + Math.max(0, Math.min(20, b[k])) * w[k], 0);
  const max = (Object.values(w) as number[]).reduce((a, x) => a + x, 0) * 20;
  return Math.round((total / max) * 100);
}

/** Words that break this round's rule, or null. Draft: 8 words max; final: 30. Taboo bans the obvious words (and simple plurals). */
export function promptProblem(text: string, pass: 'draft' | 'final', taboo: string[] | null): string | null {
  const t = text.trim();
  if (!t) return 'Write a prompt first.';
  if (t.length > 320) return 'Keep it under 320 characters.';
  const words = t.split(/\s+/).length;
  const max = pass === 'draft' ? 8 : 30;
  if (words > max) return `Your ${pass} can be at most ${max} words (you have ${words}).`;
  for (const w of taboo || []) {
    if (new RegExp(`\\b${w.replace(/[^a-z0-9]/gi, '')}(s|es)?\\b`, 'i').test(t)) return `“${w}” is a taboo word this round. Describe it another way.`;
  }
  return null;
}
